name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@2.29.0
      with:
        php-version: '8.2'
        tools: cs2pr, phpcs
    - name: Run phpcs
      run: phpcs -q --report=checkstyle src/ tests/ | cs2pr

  unit-tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-versions: ['8.1', '8.2']
    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@2.29.0
      with:
        php-version: ${{ matrix.php-versions }}
        tools: composer, phpunit
    - name: Install dependencies
      run: composer install
    - name: PHPUnit
      run: phpunit --coverage-clover coverage.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: unittests
